openapi: "3.0.3"
info:
  title: Finances App APIs
  version: "1.0"
servers:
  - url: /
paths:
  /test:
    get:
      operationId: "test"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Account"
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        monthlyLimit:
          type: integer
        yearlyLimit:
          type: integer
        type:
          type: string
          $ref: "#/components/schemas/CategoryType"
        subCategories:
          type: array
          items:
            $ref: "#/components/schemas/SubCategory"
    CategoryType:
      type: string
      enum:
        - Needs
        - Wants
        - Savings
        - Income
    SubCategory:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        categoryId:
          type: integer
    Transaction:
      type: object
      properties:
        id:
          type: integer
        accountId:
          type: integer
        categoryId:
          type: integer
        transferAccountId:
          type: integer
        timestamp:
          type: string
        title:
          type: string
        narration:
          type: string
        amount:
          type: integer
