

# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - finances-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      
      - name: Cleanup dist folder
        run: rm -rf dist

      - name: Build client
        run: |
          cd client
          npm install
          npm run build --if-present

      - name: Build server
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: |
          mv client/build dist/static
          zip release.zip ./dist package.json package-lock.json -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F09E032F5B3B4CE0BBBEFF12CDF9DFFA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9FF2495E590147CEA29CC28B1739601E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_33245682DEEE4AF69C9B9E0C0A55004F }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'finances-app'
          slot-name: 'Production'
          package: .
          
